### ISSUE TITLE
Comparing two deltas for equality

### ISSUE THREAD

**Issue by spectras** [quilljs/delta#15]
Hello,

Given two documents in delta format, is there a provided way to tell whether they represent the same content? I simply need to enable / disable a "dirty" flag.

I see a naive way, by generating the `diff` and checking whether it is empty, however it is a costly operation. So:

 * Did I miss the function somewhere?
 * Or, can you validate this approach: given deltas have a canonical format, two identical documents must have the same representation. Therefore I can walk the operations of both deltas, comparing their content. If all match, then the deltas represent identical documents.

Thanks for your time. I love quilljs' approach to editing. At last I can represent semantic elements in my documents and not formatting. CityBlot, …

**Comment by jhchen** [comment]
The latter is true so you can walk it if you want but you can also just use a library's object comparison method like lodash's isEqual.

**Comment by spectras** [comment]
Thanks for your fast answer. Keep up the good work :)
