### ISSUE TITLE
Error on converting Delta to JSON

### ISSUE THREAD

**Issue by livthomas** [quilljs/delta#20]
The README file says that it should be possible to convert Delta to string using `JSON.stringify()`. However, when I try to serialize a simple delta, I get the following error:
```
TypeError: Converting circular structure to JSON
```
Is this a bug or am I doing something wrong? I use Quill 1.3.4 integrated to my Angular application through `ngx-quill` library.

**Comment by livthomas** [comment]
It seems that the error only occurs when I try to serialize Delta with my custom Blot. Some guidelines on how to create your custom blots would be very useful since it is not clear from the existing materials.

**Comment by jhchen** [comment]
Deltas are not doing anything special here -- they are just Javascript objects and all normal JSON stringification constraints apply, such as the circular reference one you encountered. Please consult the JSON documentation for what you can and cannot stringify.
