### ISSUE TITLE
Ability to use own diff() function

### ISSUE THREAD

**Issue by volser** [quilljs/delta#25]
Sometimes `fast-diff` function works not very well.

This library https://github.com/liddiard/text-diff
with `cleanupSemantic` works much better.

So it would be cool to add ability to use own `diff` function.

for example add optional param here
`Delta.prototype.diff = function (other, index, diffFunction?)`

**Comment by volser** [comment]
![image](https://user-images.githubusercontent.com/10529385/43010779-151e945e-8c4a-11e8-85d5-922a4b8ea355.png)

**Comment by jhchen** [comment]
Can you run a comparison with two slightly similar texts instead of two completely different texts?

**Comment by volser** [comment]
what if I have two completely different texts?

**Comment by jhchen** [comment]
I'm unclear on the criteria for "much better". From the visual comparison it looks like it is just "fewer" diffs which does not seem like a compelling criteria. Why not just have a complete replacement then? Comparisons on real world scenarios seem more useful which is the priority for this project. If this does not align with your needs this is an open source project so feel free to fork and customize to your liking. Adding complexity to the API surface and increasing maintenance burden is not something I will do lightly.
