### ISSUE TITLE
Could we have an `undoCompose` function? For calculating the reverse of a delta when composed with a base delta.

### ISSUE THREAD

**Issue by jaredly** [quilljs/delta#28]
E.g. this would make undo simpler / faster.

The quilljs history module has a [guessUndoDelta](https://github.com/quilljs/quill/blob/develop/modules/history.js#L137), which can only guess the undo of an insert, understandably -- you need the base delta to be able to calculate the undo of a delete, for example.

So I'm envisioning a `delta.undoCompose(baseDelta)` such that the following holds true for any delta:
```
const undo = delta.undoCompose(baseDelta);
deepEqual(baseDelta.compose(delta).compose(undo), baseDelta)
```

**Comment by jaredly** [comment]
Right, you wouldn't be storing the `baseDelta`s. I'm envisioning this as a better way to do `diff()` that is aware of what the delta was that is making the change.
So instead of
```
const undoDelta = baseDelta.compose(delta).diff(baseDelta);
```
you can do
```
const undoDelta = delta.undoCompose(baseDelta)
```

**Comment by jhchen** [comment]
I see what you mean now. `baseDelta` needs to be an insert-only delta I believe but `delta` can be an arbitrary delta in your examples. I can see its use for undo and could replace guessUndoDelta. Are there other use cases though? If not it should arguably belong in Quill instead of here. Either way is this something you'd be willing to contribute a PR to?

**Comment by jhchen** [comment]
Great thanks! Let me know when there is something to look at or if you have questions getting started.

**Comment by jhchen** [comment]
Hey is this something you are still planning on working on? We were planning on adding this soon if not.

**Comment by jaredly** [comment]
I haven't gotten to this yet, it's a little farther down on my priority list
