### ISSUE TITLE
Add a way to render html using delta

### ISSUE THREAD

**Issue by priyashpatil** [quilljs/delta#37]
Currently theres no elegant way to convert delta to html.
to do that even the delta is independent from quill. I found found people are using solutions like

```
function quillGetHTML(inputDelta) {
    var tempCont = document.createElement("div");
    (new Quill(tempCont)).setContents(inputDelta);
    return tempCont.getElementsByClassName("ql-editor")[0].innerHTML;
}
```
I like the the concept of deltas but the. I don't want to render editor for blog site in frontend.

**Comment by priyashpatil** [comment]
found solutions at awesome-quill repository.

**Comment by alexbjorlig** [comment]
Can you share how you solved the issue?

**Comment by mahdyaslami** [comment]
I used this:

```js
let html = quill.root.innerHTML
```

@alexbjorlig
