### ISSUE TITLE
diff() and Unicode surrogate pairs

### ISSUE THREAD

**Issue by Calyhre** [quilljs/delta#40]
Since `quill-delta` has moved to `fast-diff@1.2.0`, who now is unicode-safe (https://github.com/jhchen/fast-diff/pull/4), using `.diff()` on document that has a `retain` leading to a unicode surrogate pair being broke, there is a `Maximum call stack size exceeded` error.

Here is in 4.0.1 without error: https://repl.it/repls/PungentColorfulScandisk
And in 4.1.0 with the error: https://repl.it/repls/FrailLimitedCoolingfan

My guess is that as `quill-delta` is not unicode-safe, any used dependency shouldn't be neither

**Comment by jhchen** [comment]
This seems to be a bug with fast-diff. Can you post an issue there?

**Comment by Calyhre** [comment]
Will do, but that would still be an issue to have a unicode aware dependency and not `quill-delta` no?

**Comment by jhchen** [comment]
quill-delta's unicode awareness comes from fast-diff
