### ISSUE TITLE
Delta diff() method returning wrong value..

### ISSUE THREAD

**Issue by naveenrsaradhya** [quilljs/delta#45]
Old Text : I am Naveen
New Text : I am visakh
                 I am soumya

I tried find difference between above two versions ...

Old Delta :  "{"ops":[{"insert":"I am Naveen\n"}]}"
New Delta : "{"ops":[{"insert":"I am visakh\nI am soumya\n"}]}"

Diff it is giving as  :  "{"ops":[{"retain":5},{"insert":"vis"},{"delete":1},{"retain":1},{"insert":"kh\nI am soumya"},{"delete":4}]}"

Here after "vis" insertion it is giving as deleted 1 which is wrong.
It should give as visakh inserted then delete right ??
Do am wrong??

**Comment by jhchen** [comment]
It's doing a character level diff not word level and the output is correct.

**Comment by naveenrsaradhya** [comment]
Ok even character also there character no match..
up to I am is correct after Naveen and visakh  if compare character level still wrong answer right?

**Comment by jhchen** [comment]
I've checked again and the output is correct. I don't know where the misunderstanding is but suggest you re-review the documentation and play around with different simpler inputs.
