### ISSUE TITLE
Replacing an insert with another insert

### ISSUE THREAD

**Issue by rsdrsd** [quilljs/delta#5]
If I have a delta which consists of some inserts and now I want to replace a certain insert (no text but an object with some properties) with another insert (no text but an object). What is the best practice for this? I read that it is not done to create your own set of operations manually, but how is it done then? I see some functions, but I can't find a proper one.

**Comment by jhchen** [comment]
What's the use case?

**Comment by rsdrsd** [comment]
When someone adds an image, it first inserts some div as blockembed, with the filename as text and a unique identifier as dataset. Then the image starts uploading to the server and also sends the uniwue identifier to the server. When image has been uploaded, the server responds with the url of that image and the unique identifier. The div with the corresponding identifier needs to be replaced with an image tag.

For this use case I need to be able to search the delta for an object with that certain identifier and get its position so that I can do: delta.retain(x).insert(...).delete(1). How do I calculate x?

**Comment by jhchen** [comment]
I think this is the wrong layer of abstraction for what you are trying to accomplish, which is why best practice is to not generate Deltas yourself.

It sounds like you are using Quill and Parchment and it would be less error prone to have blockembed replace itself with the real image blot instead.

**Comment by rsdrsd** [comment]
Yes, I am trying to build a custom editor based on the "cloning medium with parchment" tutorial. I've built some blots and now I need to replace a blot with another blot. 

Now your advice is to let the blockembed replace itself with another blot. Now I have two questions:

- Which function inside the blockembed class should be overriden to do the replacement?
- When the upload is finished an event is triggered. How do I get a reference to the right blot, depending on the sequence number?

**Comment by jhchen** [comment]
Are you using just Parchment or Quill as well?

**Comment by rsdrsd** [comment]
I am also using Quill. It would be great to see some examples, because for now I only see insertText and insertEmbed functions. I think I have to use Parchment.find to find the corresponding blot by a node. But if I have the blot, How do I delete it properly?

**Comment by rsdrsd** [comment]
I think I've found a solution, correct me if I am wrong:
```
let node = document.querySelectorAll(`[data-sequence="${sequence}"]`);
let blot = Parchment.find(node);
let image = {src, alt, class, type, sequence};
blot.replaceWith('image', image);
```
Thanks for your feedback and wonderful editor!

**Comment by rsdrsd** [comment]
Well after some testing, if I do
```
console.log(quill.getContents());
```
after the replace, the content in the editor is updated, but the delta isn't.
