### ISSUE TITLE
Best way to save delta file in database

### ISSUE THREAD

**Issue by duomoteng** [quilljs/delta#52]
Hi, I am working on an app that uses delta as the rich text format.
I need to save the rich text in my SQLite database. I want to know what is the best method to save it. For example, save the whole JSON file in the database or save each command as a row?

**Comment by jhchen** [comment]
Please use Issues for bug reports or feature requests

**Comment by kevinlu1248** [comment]
I am wondering the same thing. Where should this be asked if issues is not the best place?
