### ISSUE TITLE
Circular dependency between Op and Iterator

### ISSUE THREAD

**Issue by stigi** [quilljs/delta#57]
Hi there,

I'm using `quill-delta` (version `4.2.2`) in a react native app (version `0.62.2`), as a format for rich text editing. 

During bundle time I'm getting the following warning:
```
Require cycle: node_modules/quill-delta/dist/Op.js -> node_modules/quill-delta/dist/Iterator.js -> node_modules/quill-delta/dist/Op.js
```

And looking at the code it's clear to see that the two files are importing from each other.

Would it be possible to get rid of `Op.iterator` and calling `new Iterator(ops)` directly from `delta.ts`?

**Comment by marcusnewton** [comment]
Bump

I've run into this issue which in my case is preventing me from submitting rich-text ops via ShareDB.

**Comment by wachunga** [comment]
This appears to still be an issue. See also https://github.com/quilljs/delta/issues/49

**Comment by marcusnewton** [comment]
Bump

**Comment by zaiisao** [comment]
Also experiencing this issue!

**Comment by jhchen** [comment]
https://github.com/quilljs/delta/pull/58 was manually merged
