### ISSUE TITLE
Feature request: Delta interface

### ISSUE THREAD

**Issue by dsebastien** [quilljs/delta#63]
It would be nice to have a Delta interface in addition to the class. That way, we could describe existing serialized data accurately, without having to create class instances.

As far as I understand this; such an interface could be as simple as:

```
interface QuillDelta {
 ops: Op[];
}
```

Does this exist somewhere already?

**Comment by rockwotj** [comment]
The @types/quill package has a DeltaStatic IIRV

**Comment by reed-lawrence** [comment]
I believe it only has a DeltaOperations static. I'm having difficulty utilizing Delta in typescript models without casting.

**Comment by Maximaximum** [comment]
This would be extremely useful!

**Comment by jhchen** [comment]
This is too small of an interface (we even just inline in delta.ts) to be helpful enough to support and maintain.
