### ISSUE TITLE
Definition of "document" vs "non-document" delta

### ISSUE THREAD

**Issue by x11x** [quilljs/delta#81]
Hi,

Am I correct in understanding that a "document" delta is one which contains only "insert" operations? Are there additional constraints? i.e. it must end with a newline?
A "non-document" is the inverse?

I can't find this documented anywhere. Do you think it would be worth adding a sentence or two explaining this distinction at the start of the Readme somewhere, since the API docs refer to "document" and "non-document" deltas?

Thanks

**Comment by jhchen** [comment]
It's meant to be explained in the third paragraph of the Readme. A non-document is simply a delta that is not a document. So it does not only have inserts.
